name: Hoge
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  hoge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "hogehoge"
      - uses: actions/checkout@v4