name: Parameter Test
on:
  workflow_dispatch:
    inputs:
      word:
        type: string
        default: fugafuga
        required: true
        description: input me!
defaults:
  run:
    shell: bash
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "入力されたワードは${{ inputs.word }}です"