name: アノテーションのテスト
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  log:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "::error::エラーだよ！"
      - run: echo "::warning::わーにんぐだよ！！"
      - run: echo "::notice::hogehogefugafuga"